In [22]:
#import necessary packages
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from scipy.stats import norm
from pandas_datareader import data
from datetime import datetime

df_GC = pd.read_csv('./data/Consumer_1_2010-2011_GC.csv',
                    parse_dates={'Date': [2,3,4]}, 
                    date_parser=lambda x: pd.datetime.strptime(x, '%d %m %Y'))

df_GC.head()

,Date,Customer_No,Consumption_Category,00:00,00:30,01:00,01:30,02:00,02:30,03:00,...,19:30,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,Total
0,2010-07-01,1,GC,0.303,0.471,0.083,0.121,0.361,0.079,0.122,...,0.540,0.406,0.543,0.495,0.216,0.378,0.128,0.078,0.125,31.984
1,2010-07-02,1,GC,0.116,0.346,0.122,0.079,0.120,0.107,0.343,...,1.100,1.012,0.817,0.526,0.335,0.402,0.142,0.120,0.111,27.166
2,2010-07-03,1,GC,0.730,1.389,0.792,0.699,0.729,0.724,0.933,...,0.387,0.274,0.782,0.519,0.225,0.123,0.157,0.390,0.124,25.526
3,2010-07-04,1,GC,0.155,0.095,0.149,0.377,0.123,0.150,0.096,...,0.992,0.462,0.379,0.505,0.586,0.269,0.252,0.295,0.232,35.873
4,2010-07-05,1,GC,0.295,0.481,0.407,0.285,0.122,0.128,0.349,...,0.945,0.385,0.295,1.034,0.169,0.122,0.135,0.079,0.378,31.278

In [44]:
avg_incr_period_1_July = [math.log(df_GC.iloc[i+1,3]/df_GC.iloc[i,3]) for i in range(31)]
avg_incr_period_1_July.pop(30)

print(avg_incr_period_1_July,len(avg_incr_period_1_July),sum(avg_incr_period_1_July.pop(30))/30)

IndexError: pop index out of range